### ISSUE TITLE
permission denied

### ISSUE THREAD

**Issue by slash31** [42wim/docker-netdot_deploy#2]
Hello, and thanks for contributing this container!

When attempting to start it, I receive the following error:

exec: "/usr/local/bin/run": permission denied
Error response from daemon: Cannot start container 3a028764eb342940bbbda1de9b8da54ba14240bb1691fe5e74a0be5809bc3779: [8] System error: exec: "/usr/local/bin/run": permission denied

This is on a CentOS7 host that's fully updated, running docker 1.9.1.

Any ideas?

**Comment by nathanloop** [comment]
I'm also having this same issue.

Seems like the /usr/local/bin/run within the docker image doesn't have a +x flag set on it
